import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="flex w-full flex-col">
          <p>
            Get started by editing&nbsp;
            <code>pages/index.tsx</code>
          </p>
        </div>
      </main>
    </>
  );
}
